// src/ui/Hero/HeroHeading.vue
<template>
  <div class="heading">
    <h2 class="title">Agent<br />Infrastructure</h2>
    <p class="description">
      Every coding agent running on this machine, mapped as a living city — one tower per tool,
      one house per live session.
    </p>
  </div>
</template>

<style scoped>
.heading {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.title {
  font-size: 36px;
  font-weight: 400;
  line-height: 1.08;
  letter-spacing: -1px;
}

.description {
  font-size: 14px;
  line-height: 1.55;
  color: var(--text-2);
}
</style>

// src/ui/Hero/HeroHeading.tsx
import styles from "./HeroHeading.module.css";

export function HeroHeading() {
  return (
    <div className={styles.heading}>
      <h1 className={styles.title}>
        Agent
        <br />
        Infrastructure
      </h1>
      <p className={styles.description}>
        Every coding agent running on this machine, mapped as a living city — one tower per tool,
        one house per live session.
      </p>
    </div>
  );
}
