// src/scene/house/House.vue
<script setup lang="ts">
import { computed, ref, shallowRef } from "vue";
import type { Group, Object3D } from "three";
import type { AgentStatus, ProviderId } from "../../domain/types";
import { PALETTE } from "../../domain/palette";
import { housePhase, houseVisual } from "../../domain/houseVisuals";
import { useCursor } from "../../composables/useCursor";
import { useDoneRipple } from "../../composables/useDoneRipple";
import { useHouseMotion } from "../../composables/useHouseMotion";
import { usePressClick } from "../../composables/usePressClick";
import { useHoverStore } from "../../stores/hover";
import { HOUSE_TOP, selectionRingGeometry } from "../geometries";
import { labelLift } from "../layout";
import { selectionRingMaterial } from "../materials";
import GroundPulse from "./GroundPulse.vue";
import HouseBeacon from "./HouseBeacon.vue";
import HouseLabel from "./HouseLabel.vue";
import HouseMarker from "./HouseMarker.vue";
import HouseShell from "./HouseShell.vue";

const props = defineProps<{
  id: string;
  provider: ProviderId;
  status: AgentStatus;
  title: string;
  percent: number | null;
  /** 0-based index and ring within the district (label stagger). */
  index: number;
  ring: number;
  /** Target offset from the tower; the house eases towards it. */
  x: number;
  z: number;
  selected: boolean;
  /** Meshes (the district tower) that can hide this house's label. */
  occluders: () => readonly (Object3D | null)[];
}>();
const emit = defineEmits<{ select: [id: string] }>();

// Template refs to three.js objects are plain shallowRefs: in dev builds useTemplateRef
// returns a readonly view that silently drops every mutation to a three.js object.
const group = shallowRef<Group | null>(null);
const initial: [number, number, number] = [props.x, 0, props.z];
const pointerOver = ref(false);
const hover = useHoverStore();
const hovered = computed(() => hover.hoveredId === props.id);
const visual = computed(() => houseVisual(props.status, props.provider));
const phase = computed(() => housePhase(props.id));
const ripples = useDoneRipple(() => props.status);
useCursor(pointerOver);
useHouseMotion(group, () => props.x, () => props.z, () => hovered.value || props.selected);

const select = () => emit("select", props.id);
const enter = () => hover.set(props.id);
const leave = () => hover.clear(props.id);
const press = usePressClick(select, { stop: true });

function onPointerover(event: { stopPropagation(): void }) {
  event.stopPropagation();
  pointerOver.value = true;
  enter();
}
function onPointerout() {
  pointerOver.value = false;
  leave();
}
</script>

<!-- One live session: shell + status effects + name label (or marker when selected). -->
<template>
  <TresGroup
    ref="group"
    :position="initial"
    @pointerdown="press.onPointerdown"
    @pointerup="press.onPointerup"
    @pointerover="onPointerover"
    @pointerout="onPointerout"
  >
    <HouseShell :visual="visual" :phase="phase" :hovered="hovered" />
    <HouseBeacon :visual="visual" :phase="phase" />
    <GroundPulse v-if="visual.groundPulse" :hex="visual.hex" loop />
    <GroundPulse v-if="ripples > 0" :key="ripples" :hex="PALETTE.blue" />
    <template v-if="selected">
      <TresMesh :geometry="selectionRingGeometry" :material="selectionRingMaterial" :position-y="0.06" />
      <HouseMarker :position="[0, HOUSE_TOP + 0.05, 0]" :title="title" :percent="percent" />
    </template>
    <HouseLabel
      v-else
      :title="title"
      :status="status"
      :opacity="visual.labelOpacity"
      :hovered="hovered"
      :lift="labelLift(index, ring)"
      :occluders="occluders"
      @select="select"
      @enter="enter"
      @leave="leave"
    />
  </TresGroup>
</template>

// src/scene/house/House.tsx
import { memo, useCallback, useMemo, useRef, useState, type RefObject } from "react";
import type { ThreeEvent } from "@react-three/fiber";
import { useCursor } from "@react-three/drei";
import type { Group, Object3D } from "three";
import type { AgentStatus, ProviderId } from "../../domain/types";
import { PALETTE } from "../../domain/palette";
import { housePhase, houseVisual } from "../../domain/houseVisuals";
import { useHoverStore, useIsHovered } from "../../state/HoverContext";
import { HOUSE_TOP, selectionRingGeometry } from "../geometries";
import { selectionRingMaterial } from "../materials";
import { CLICK_TOLERANCE_PX } from "../Ground";
import { labelLift } from "../layout";
import { GroundPulse } from "./GroundPulse";
import { HouseBeacon } from "./HouseBeacon";
import { HouseLabel } from "./HouseLabel";
import { HouseMarker } from "./HouseMarker";
import { HouseShell } from "./HouseShell";
import { useDoneRipple } from "./useDoneRipple";
import { useHouseMotion } from "./useHouseMotion";

interface HouseProps {
  id: string;
  provider: ProviderId;
  status: AgentStatus;
  title: string;
  percent: number | null;
  /** 0-based index and ring within the district (label stagger). */
  index: number;
  ring: number;
  /** Target offset from the tower; the house eases towards it. */
  x: number;
  z: number;
  selected: boolean;
  onSelect: (id: string) => void;
  /** Meshes (the district tower) that can hide this house's label. */
  occluders: RefObject<Object3D>[];
}

/** One live session: shell + status effects + name label (or marker when selected). */
export const House = memo(function House(props: HouseProps) {
  const { id, provider, status, title, percent, index, ring, x, z, selected, onSelect, occluders } = props;
  const group = useRef<Group>(null);
  const [initial] = useState<[number, number, number]>(() => [x, 0, z]);
  const [pointerOver, setPointerOver] = useState(false);
  const hover = useHoverStore();
  const hovered = useIsHovered(id);
  const visual = useMemo(() => houseVisual(status, provider), [status, provider]);
  const phase = useMemo(() => housePhase(id), [id]);
  const ripples = useDoneRipple(status);
  useCursor(pointerOver);
  useHouseMotion(group, x, z, hovered || selected);

  const select = useCallback(() => onSelect(id), [onSelect, id]);
  const enter = useCallback(() => hover.set(id), [hover, id]);
  const leave = useCallback(() => hover.clear(id), [hover, id]);
  const onClick = (event: ThreeEvent<MouseEvent>) => {
    event.stopPropagation();
    if (event.delta <= CLICK_TOLERANCE_PX) select();
  };

  return (
    <group
      ref={group}
      position={initial}
      onClick={onClick}
      onPointerOver={(e) => {
        e.stopPropagation();
        setPointerOver(true);
        enter();
      }}
      onPointerOut={() => {
        setPointerOver(false);
        leave();
      }}
    >
      <HouseShell visual={visual} phase={phase} hovered={hovered} />
      <HouseBeacon visual={visual} phase={phase} />
      {visual.groundPulse && <GroundPulse hex={visual.hex} loop />}
      {ripples > 0 && <GroundPulse key={ripples} hex={PALETTE.blue} />}
      {selected ? (
        <>
          <mesh geometry={selectionRingGeometry} material={selectionRingMaterial} position-y={0.06} />
          <HouseMarker position={[0, HOUSE_TOP + 0.05, 0]} title={title} percent={percent} />
        </>
      ) : (
        <HouseLabel
          title={title}
          status={status}
          opacity={visual.labelOpacity}
          hovered={hovered}
          lift={labelLift(index, ring)}
          onSelect={select}
          onEnter={enter}
          onLeave={leave}
          occluders={occluders}
        />
      )}
    </group>
  );
});
