// src/ui/CameraControls.tsx
import { RotateCcw, Scan, ZoomIn, ZoomOut, type LucideIcon } from "lucide-react";
import { useCameraRig } from "../scene/useCameraRig";
import type { CameraRig } from "../scene/cameraRig";
import { IconButton } from "./common/IconButton";
import styles from "./CameraControls.module.css";

const BUTTONS: ReadonlyArray<{ label: string; Icon: LucideIcon; run: (rig: CameraRig) => void }> = [
  { label: "Zoom in", Icon: ZoomIn, run: (rig) => rig.zoomIn() },
  { label: "Zoom out", Icon: ZoomOut, run: (rig) => rig.zoomOut() },
  { label: "Reset view angle", Icon: RotateCcw, run: (rig) => rig.reset() },
  { label: "Fit city to view", Icon: Scan, run: (rig) => rig.fit() },
];

/** 44px round glass buttons, bottom-left above the subagent strip. */
export function CameraControls() {
  const rig = useCameraRig();
  return (
    <div className={styles.controls} role="toolbar" aria-label="Camera">
      {BUTTONS.map(({ label, Icon, run }) => (
        <IconButton key={label} label={label} shape="round" size={44} onClick={() => run(rig)}>
          <Icon size={18} aria-hidden />
        </IconButton>
      ))}
    </div>
  );
}

// src/ui/CameraControls.vue
<script setup lang="ts">
import { useCameraRigStore } from "../stores/cameraRig";
import { CAMERA_COMMANDS } from "./cameraCommands";
import IconButton from "./common/IconButton.vue";

const rig = useCameraRigStore();
</script>

<!-- 44px round glass buttons, bottom-left above the subagent strip. -->
<template>
  <div class="controls" role="toolbar" aria-label="Camera">
    <IconButton
      v-for="command in CAMERA_COMMANDS"
      :key="command.label"
      :label="command.label"
      shape="round"
      :size="44"
      @click="command.run(rig)"
    >
      <component :is="command.Icon" :size="18" aria-hidden="true" />
    </IconButton>
  </div>
</template>

<style scoped>
.controls {
  position: absolute;
  left: var(--gutter);
  bottom: calc(var(--gutter) + var(--strip-space, 0px));
  display: flex;
  gap: 8px;
  pointer-events: auto;
  transition: bottom 260ms var(--ease-out);
}
</style>
