// src/scene/CityScene.vue
<script setup lang="ts">
import { computed } from "vue";
import { storeToRefs } from "pinia";
import type { ProviderMeta } from "../domain/providers";
import { useSelectionStore } from "../stores/selection";
import type { CityModel } from "./cityModel";
import District from "./District.vue";
import Ground from "./Ground.vue";

const props = defineProps<{ city: CityModel }>();
const selectionStore = useSelectionStore();
const { selection } = storeToRefs(selectionStore);
const selectedProvider = computed(
  () => props.city.districts.find((d) => d.houses.some((h) => h.session.id === selection.value.sessionId))?.provider,
);
const onFocus = (meta: ProviderMeta) => selectionStore.focusProvider(meta.id);
</script>

<!-- Ground + all four districts, wired to the shared selection state. -->
<template>
  <Ground @deselect="selectionStore.clearSession()" />
  <District
    v-for="district in city.districts"
    :key="district.provider"
    :district="district"
    :highlighted="selection.provider === district.provider || selectedProvider === district.provider"
    :selected-id="selection.sessionId"
    @select-house="selectionStore.selectSession($event)"
    @focus="onFocus"
  />
</template>

// src/scene/CityScene.tsx
import { useCallback } from "react";
import type { ProviderMeta } from "../domain/providers";
import { useSelection } from "../state/SelectionContext";
import type { CityModel } from "./cityModel";
import { District } from "./District";
import { Ground } from "./Ground";

/** Ground + all four districts, wired to the shared selection state. */
export function CityScene({ city }: { city: CityModel }) {
  const { selection, selectSession, clearSession, focusProvider } = useSelection();
  const onFocus = useCallback((meta: ProviderMeta) => focusProvider(meta.id), [focusProvider]);
  const selectedProvider = city.districts.find((d) =>
    d.houses.some((h) => h.session.id === selection.sessionId),
  )?.provider;

  return (
    <>
      <Ground onDeselect={clearSession} />
      {city.districts.map((district) => (
        <District
          key={district.provider}
          district={district}
          highlighted={selection.provider === district.provider || selectedProvider === district.provider}
          selectedId={selection.sessionId}
          onSelectHouse={selectSession}
          onFocus={onFocus}
        />
      ))}
    </>
  );
}
