// src/scene/CityCanvas.tsx
import { useMemo, useRef } from "react";
import { Canvas } from "@react-three/fiber";
import { PALETTE } from "../domain/palette";
import { useSnapshot } from "../state/SnapshotContext";
import { useSelection } from "../state/SelectionContext";
import { buildCity } from "./cityModel";
import { CityScene } from "./CityScene";
import { CameraRigBinding } from "./CameraRigBinding";
import { Effects } from "./Effects";
import { FrameThrottle } from "./FrameThrottle";
import { LabelLayerContext } from "./LabelLayer";
import { Lights } from "./Lights";
import styles from "./CityCanvas.module.css";

const CAMERA = { position: [60, 60, 60] as [number, number, number], zoom: 22, near: 0.1, far: 1000 };
/**
 * The EffectComposer renders the scene into its own buffer (with its own
 * depth), so the canvas only receives the final full-screen pass: it needs no
 * depth buffer, and an opaque canvas is cheaper for the compositor to blend.
 */
const GL = { antialias: false, alpha: false, depth: false };
/**
 * Capped below Retina 2×: under bloom + FXAA it reads almost the same, and
 * every full-screen buffer (canvas, composer, bloom) shrinks by ~44% — about
 * 100 MB less GPU memory.
 */
const DPR: [number, number] = [1, 1.5];

/** Full-bleed isometric WebGL city behind the UI overlay. */
export function CityCanvas() {
  const { snapshot } = useSnapshot();
  const { selection } = useSelection();
  const city = useMemo(() => buildCity(snapshot), [snapshot]);
  const labels = useRef<HTMLDivElement>(null);

  return (
    <div className={styles.layer}>
      <LabelLayerContext.Provider value={labels}>
        <Canvas
          orthographic
          frameloop="demand"
          shadows="percentage"
          dpr={DPR}
          camera={CAMERA}
          gl={GL}
        >
          <FrameThrottle />
          <color attach="background" args={[PALETTE.bg]} />
          <fog attach="fog" args={[PALETTE.bg, 110, 175]} />
          <Lights />
          <CityScene city={city} />
          <CameraRigBinding city={city} hasData={snapshot != null} focusedProvider={selection.provider} />
          <Effects />
        </Canvas>
      </LabelLayerContext.Provider>
      <div ref={labels} className={styles.labels} />
    </div>
  );
}

// src/scene/CityCanvas.vue
<script setup lang="ts">
import { computed, provide, useTemplateRef } from "vue";
import { storeToRefs } from "pinia";
import { TresCanvas } from "@tresjs/core";
import { Color, NoToneMapping, PCFShadowMap } from "three";
import { PALETTE } from "../domain/palette";
import { labelLayerKey } from "../composables/useLabelLayer";
import { useSelectionStore } from "../stores/selection";
import { useSnapshotStore } from "../stores/snapshot";
import { buildCity } from "./cityModel";
import CameraRigBinding from "./CameraRigBinding.vue";
import CityScene from "./CityScene.vue";
import Effects from "./Effects.vue";
import FrameDriver from "./FrameDriver.vue";
import Lights from "./Lights.vue";

const CAMERA_POSITION: [number, number, number] = [60, 60, 60];
/**
 * Capped below Retina 2×: under bloom + FXAA it reads almost the same, and
 * every full-screen buffer (canvas, composer, bloom) shrinks by ~44% — about
 * 100 MB less GPU memory.
 */
const DPR: [number, number] = [1, 1.5];
/** Scene background, matching the page behind the canvas and the fog. */
const background = new Color(PALETTE.bg);

const { snapshot } = storeToRefs(useSnapshotStore());
const { selection } = storeToRefs(useSelectionStore());
const city = computed(() => buildCity(snapshot.value));

const labels = useTemplateRef<HTMLDivElement>("labels");
provide(labelLayerKey, labels);
</script>

<!-- Full-bleed isometric WebGL city behind the UI overlay. -->
<template>
  <div class="layer">
    <!--
      The scene composer replaces TresJS's render, so the canvas only receives the
      final full-screen pass: no depth buffer needed, and an opaque canvas is
      cheaper for the compositor to blend. No tone mapping: the HDR emissives
      feed bloom untouched.
    -->
    <TresCanvas
      :dpr="DPR"
      :antialias="false"
      :alpha="false"
      :depth="false"
      shadows
      :shadow-map-type="PCFShadowMap"
      :tone-mapping="NoToneMapping"
    >
      <FrameDriver />
      <TresOrthographicCamera :position="CAMERA_POSITION" :zoom="22" :near="0.1" :far="1000" />
      <primitive :object="background" attach="background" />
      <TresFog attach="fog" :args="[PALETTE.bg, 110, 175]" />
      <!-- First, so the controls update before the labels project each frame. -->
      <CameraRigBinding :city="city" :has-data="snapshot != null" :focused-provider="selection.provider" />
      <Lights />
      <CityScene :city="city" />
      <Effects />
    </TresCanvas>
    <div ref="labels" class="labels" />
  </div>
</template>

<style scoped>
.layer {
  position: absolute;
  inset: 0;
  z-index: 0;
  /* Own stacking context: in-scene HTML labels can never cover the overlay. */
  isolation: isolate;
}

/* Same box as the canvas so the Html labels' projected coordinates line up. */
.labels {
  position: absolute;
  inset: 0;
  z-index: 1;
  overflow: hidden;
  pointer-events: none;
}
</style>
