// src/ui/AgentPanel/AgentPanel.vue
<script setup lang="ts">
import { cssVar } from "../../domain/palette";
import type { SelectedSession } from "../../domain/session";
import ContextBar from "./ContextBar.vue";
import MetaRows from "./MetaRows.vue";
import PanelActions from "./PanelActions.vue";
import PanelHeader from "./PanelHeader.vue";
import PanelStats from "./PanelStats.vue";
import ProgressSection from "./ProgressSection.vue";

defineProps<{ selected: SelectedSession }>();
const emit = defineEmits<{ back: []; close: [] }>();
</script>

<!-- Detail panel for the selected house; lives in the right column in place of the list. -->
<template>
  <aside
    class="glass panel"
    :style="{ '--accent': cssVar(selected.meta.color) }"
    :aria-label="`${selected.session.title} details`"
  >
    <PanelHeader
      :session="selected.session"
      :meta="selected.meta"
      :house-number="selected.houseNumber"
      @back="emit('back')"
      @close="emit('close')"
    />
    <ProgressSection :progress="selected.session.progress" :current-step="selected.session.currentStep" />
    <PanelStats :session="selected.session" />
    <ContextBar :tokens="selected.session.tokens" />
    <MetaRows :session="selected.session" />
    <PanelActions :cwd="selected.session.cwd" />
  </aside>
</template>

<style scoped>
.panel {
  min-height: 0;
  max-height: 100%;
  overflow-y: auto;
  padding: 24px;
  display: flex;
  flex-direction: column;
  gap: 20px;
  border-radius: var(--radius-panel);
  background:
    radial-gradient(260px 200px at 100% 0%, color-mix(in srgb, var(--accent) 16%, transparent), transparent 72%),
    var(--surface);
  box-shadow: 0 24px 60px rgba(0, 0, 0, 0.45);
}

.panel > * {
  flex: none;
}
</style>

// src/ui/AgentPanel/AgentPanel.tsx
import type { CSSProperties } from "react";
import { cssVar } from "../../domain/palette";
import type { SelectedSession } from "../../domain/session";
import { ContextBar } from "./ContextBar";
import { MetaRows } from "./MetaRows";
import { PanelActions } from "./PanelActions";
import { PanelHeader } from "./PanelHeader";
import { PanelStats } from "./PanelStats";
import { ProgressSection } from "./ProgressSection";
import styles from "./AgentPanel.module.css";

interface AgentPanelProps {
  selected: SelectedSession;
  /** Return to the agent list (chevron). */
  onBack: () => void;
  onClose: () => void;
}

/** Detail panel for the selected house; lives in the right column in place of the list. */
export function AgentPanel({ selected, onBack, onClose }: AgentPanelProps) {
  const { session, houseNumber, meta } = selected;
  const accent = { "--accent": cssVar(meta.color) } as CSSProperties;

  return (
    <aside className={`glass ${styles.panel}`} style={accent} aria-label={`${session.title} details`}>
      <PanelHeader session={session} meta={meta} houseNumber={houseNumber} onBack={onBack} onClose={onClose} />
      <ProgressSection progress={session.progress} currentStep={session.currentStep} />
      <PanelStats session={session} />
      <ContextBar tokens={session.tokens} />
      <MetaRows session={session} />
      <PanelActions cwd={session.cwd} />
    </aside>
  );
}
